on:
    # push:
    #  branches: 
    #    - main
    schedule:
      - cron: '0 0 */2 * *' 
  
name: Update dependencies
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
        -   name: Setup Nushell
            uses: hustcer/setup-nu@main
            with:
              version: "*"
              enable-plugins: true
        -   uses: actions/checkout@v2
        -   name: Update Dependencies list
            id: upd
            shell: nu {0}
            run: |
                nu -c '
                  cargo install cargo-edit cargo-upgrades -f
                  cargo upgrade
                  let changed = git status -s | is-empty | not $in
                  if ($changed) {
                    open Cargo.toml 
                      | upsert
                          package.version
                          ( $in 
                              | get package.version
                              | inc --patch
                          )
                      | save Cargo.toml
                  }
                  echo { "changed": $changed }
                '
                
        -   uses: EndBug/add-and-commit@v9 
            if: steps.upd.outputs.changed
            with:
                # add: Cargo.md # Only commit+push the output file 
                author_name: GitHub-Action